# Generated by Django 5.1.4 on 2025-01-22 01:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pg_app', '0009_remove_profile_solved_questions_questionrelation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='UserTagStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=50)),
                ('qualityPoints', models.IntegerField(default=0)),
                ('isSolved', models.BooleanField(default=False)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_stats', to='pg_app.profile')),
            ],
            options={
                'unique_together': {('profile', 'tag')},
            },
        ),
    ]
